CREATE TABLE ACCOUNT (
	ACCOUNT_ID VARCHAR2(50)  NOT NULL PRIMARY KEY,
	ACCOUNT_NAME VARCHAR2(50) NOT NULL,
	ACCOUNT_PASSWORD VARCHAR2(50) NOT NULL,
	ROLE VARCHAR2(50) NOT NULL
);

CREATE TABLE CUSTOMER (
	CUSTOMER_CODE VARCHAR2(50)  NOT NULL PRIMARY KEY,
	CUSTOMER_NAME VARCHAR2(50) NOT NULL,
	DATE_OF_BIRTH VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(50),
	EMAIL VARCHAR2(50),
	PHONE_NUMBER VARCHAR2(50),
	NOTES VARCHAR2(50)
);

CREATE TABLE EMPLOYEE (
	EMPLOYEE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
	DATE_OF_BIRTH VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(50),
	EMAIL VARCHAR2(50),
	PHONE_NUMBER VARCHAR2(50),
	DATE_OF_EMPLOYMENT VARCHAR2(50) NOT NULL,
	POSITION VARCHAR2(50),
	SALARY NUMBER(12,2),
	NOTES VARCHAR2(50),
	EMPLOYEE_NAME VARCHAR2(50)
);
CREATE TABLE INVOICE (
    INVOICE_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
    INVOICE_CREATION_DATE DATE NOT NULL,
    INVOICE_DETAILS VARCHAR2(200),
    TOTAL_INVOICE_AMOUNT NUMBER(12,2)
);

CREATE TABLE PET (
    PET_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
    PET_NAME VARCHAR2(50) NOT NULL,
    PET_TYPE VARCHAR2(50) NOT NULL,
    DATE_OF_ACQUISITION VARCHAR2(50) NOT NULL,
    PRICE NUMBER(12,2),
    NOTES VARCHAR2(200)
);

CREATE TABLE PRODUCT (
    PRODUCT_CODE VARCHAR2(50) NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRICE NUMBER NOT NULL,
    NOTES VARCHAR2(50),
    IMPORT_PRICE NUMBER,
    QUANTITY NUMBER,
    DATE_ADDED VARCHAR2(50)
);

CREATE TABLE SERVICE (
    SERVICE_CODE VARCHAR2(50)  NOT NULL PRIMARY KEY,
    SERVICE_NAME VARCHAR2(50)  NOT NULL,
    TYPE VARCHAR2(50)  NOT NULL,
    PRICE NUMBER  NOT NULL,
    NOTES VARCHAR2(50)
);